# Site settings
title: "Ajoy Karmakar"
name: "Ajoy Karmakar"
email: "ajoy.iirs@gmail.com"
description: "Ajoy Karmakar's personal web page"
url: "https://ajoyk11.github.io"
baseurl: ""  # Leave blank for user.github.io type site
repository: "ajoyk11/ajoyk11.github.io"
minimal_mistakes_skin: "dirt"
search: false

# Theme
remote_theme: "mmistakes/minimal-mistakes@4.24.0"

# Author information (for sidebar)
author:
  name: "Ajoy Karmakar"
  avatar: "/assets/images/me.jpg"  # Make sure this image exists
  bio: "Remote Sensing Researcher"
  location: "Leh, Ladakh, India"
  links:
    - label: "Facebook"
      icon: "fab fa-fw fa-facebook-square"
      url: "https://www.facebook.com/ajoyk11"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/ajoyk11"

# Footer social links
footer:
  links:
    - label: "LinkedIn"
      icon: "fab fa-fw fa-linkedin"
      url: "https://www.linkedin.com/in/ajoykarmakar"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/ajoyk11"

# Social Sharing Metadata
social:
  type: "Person"
  name: "Ajoy Karmakar"
  links:
    - "https://www.facebook.com/ajoyk11"
    - "https://github.com/ajoyk11"

# Analytics (optional)
analytics:
  provider: "google-gtag"
  google:
    tracking_id: "UA-34103986-3"
    anonymize_ip: false

# Build settings
markdown: kramdown
include:
  - _pages

plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jemoji
  - jekyll-include-cache

defaults:
  - scope:
      path: "_pages"
      type: pages
    values:
      layout: single
      author_profile: true

# Archives (optional)
category_archive:
  type: liquid
  path: /categories/
tag_archive:
  type: liquid
  path: /tags/
