title: "Ajoy Karmakar"
name: "Ajoy Karmakar"
email: "ajoy.iirs@gmail.com"
description: "Ajoy Karmakar's personal web page"
url: "https://ajoyk11.github.io"
baseurl: ""
repository: "ajoyk11/ajoyk11.github.io"
minimal_mistakes_skin: "dirt"
search: false

remote_theme: "mmistakes/minimal-mistakes@4.24.0"

author:
  name   : "Ajoy Karmakar"
  avatar : "/assets/images/me.jpg"
  bio    : "Remote Sensing Researcher"
  location: "Leh, Ladakh, India"
  links:
    - label: "Facebook"
      icon: "fab fa-fw fa-facebook-square"
      url: "https://www.facebook.com/ajoyk11"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/ajoyk11"

footer:
  links:
    - label: "LinkedIn"
      icon: "fab fa-fw fa-linkedin"
      url: "https://www.linkedin.com/in/ajoykarmakar"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/ajoyk11"

markdown: kramdown
include:
  - _pages

plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jemoji
  - jekyll-include-cache

defaults:
  - scope:
      path: "_pages"
      type: pages
    values:
      layout: single
      author_profile: true

category_archive:
  type: liquid
  path: /categories/
tag_archive:
  type: liquid
  path: /tags/
